#define INTCONST 1
#define LE 2
#define PROGRAMA 3
#define LEIA 4
#define ENQUANTO 5
#define IDENTIFICADOR 6
#define TYPE_CAR 7
#define TYPE_INT 8
#define RETURN 9
#define CONST_STRING 10
#define ESCREVA 11
#define NOVALINHA 12
#define SE 13
#define ENTAO 14
#define SENAO 15
#define EXECUTE 16
